version: '3'

services:
    
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - "8005:8000"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge