version: '3'

services:
    
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app-network
    # depends_on: 
    #   - db

  # db:
  #   image: postgres:13.3
  #   environment:
  #     POSTGRES_DB: "store"
  #     POSTGRES_USER: "konstantin"
  #     POSTGRES_PASSWORD: "kali"
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   volumes: 
  #     - db:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge


volumes:
  db:
    driver: local
  app:
    driver: local